---
- name: Adiciona o usu치rio HelpDesk
  ansible.builtin.user:
    name: helpdesk
    state: present
    shell: /bin/bash
    password: $1$Vf3jj9E3$DTibRWkRvP8wJqcDLJNzT1
  tags: users

- name: Adiciona o usu치rio DevOps
  ansible.builtin.user:
    name: devops
    state: present
    shell: /bin/bash
    password: $1$Vf3jj9E3$DTibRWkRvP8wJqcDLJNzT1
  tags: users

- name: Adiciona o usu치rio Roberto
  ansible.builtin.user:
    name: roberto
    state: present
    shell: /bin/bash
    password: $1$Vf3jj9E3$DTibRWkRvP8wJqcDLJNzT1
  tags: users

- name: Adiciona o usu치rio Analista
  ansible.builtin.user:
    name: analista
    state: present
    shell: /bin/bash
    password: $1$Vf3jj9E3$DTibRWkRvP8wJqcDLJNzT1
  tags: users
